
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 14 2025 12:14:27 IST (Mar 14 2025 06:44:27 UTC)

// Verification Directory fv/s298 

module s298(GND, VDD, CK, G0, G1, G117, G118, G132, G133, G2, G66, G67);
  input GND, VDD, CK, G0, G1, G2;
  output G117, G118, G132, G133, G66, G67;
  wire GND, VDD, CK, G0, G1, G2;
  wire G117, G118, G132, G133, G66, G67;
  wire G10, G11, G12, G13, G14, G15, G22, G23;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  DFFHQX1 DFF_10_q_reg(.CK (CK), .D (n_55), .Q (G132));
  DFFHQX1 DFF_9_q_reg(.CK (CK), .D (n_52), .Q (G118));
  DFFHQX1 DFF_4_q_reg(.CK (CK), .D (n_53), .Q (G14));
  DFFHQX1 DFF_6_q_reg(.CK (CK), .D (n_54), .Q (G66));
  DFFHQX1 DFF_5_q_reg(.CK (CK), .D (n_48), .Q (G15));
  DFFHQX1 DFF_3_q_reg(.CK (CK), .D (n_46), .Q (G13));
  OAI211X1 g1110__2398(.A0 (G10), .A1 (n_47), .B0 (n_32), .C0 (n_51),
       .Y (n_55));
  DFFHQX1 DFF_7_q_reg(.CK (CK), .D (n_45), .Q (G67));
  OAI211X1 g1120__5107(.A0 (n_2), .A1 (n_42), .B0 (n_50), .C0 (n_49),
       .Y (n_54));
  NOR2X1 g1114__6260(.A (G0), .B (n_44), .Y (n_53));
  NAND4XL g1109__4319(.A (n_51), .B (n_50), .C (n_37), .D (n_49), .Y
       (n_52));
  NOR2X1 g1117__8428(.A (G0), .B (n_47), .Y (n_48));
  DFFHQX1 DFF_8_q_reg(.CK (CK), .D (n_43), .Q (G117));
  DFFHQX1 DFF_1_q_reg(.CK (CK), .D (n_39), .Q (G11));
  OAI22X1 g1115__5526(.A0 (G0), .A1 (n_31), .B0 (n_38), .B1 (n_13), .Y
       (n_46));
  OAI211X1 g1123__6783(.A0 (G11), .A1 (n_41), .B0 (n_40), .C0 (n_34),
       .Y (n_45));
  DFFHQX1 DFF_11_q_reg(.CK (CK), .D (n_36), .Q (G133));
  MX2X1 g1122__3680(.A (G14), .B (n_29), .S0 (n_25), .Y (n_44));
  AOI21X1 g1125__1617(.A0 (G15), .A1 (n_27), .B0 (n_21), .Y (n_47));
  OAI211X1 g1121__2802(.A0 (n_0), .A1 (n_42), .B0 (n_41), .C0 (n_40),
       .Y (n_43));
  DFFHQX1 DFF_2_q_reg(.CK (CK), .D (n_30), .Q (G12));
  OAI32X1 g1124__1705(.A0 (G0), .A1 (G11), .A2 (n_11), .B0 (n_38), .B1
       (n_24), .Y (n_39));
  AOI22X1 g1127__5122(.A0 (G118), .A1 (n_33), .B0 (n_10), .B1 (n_9), .Y
       (n_37));
  OR2X1 g1136__8246(.A (n_35), .B (n_28), .Y (n_49));
  OAI32X1 g1129__7098(.A0 (n_18), .A1 (n_35), .A2 (n_7), .B0 (n_1), .B1
       (n_42), .Y (n_36));
  NAND2X1 g1130__6131(.A (G67), .B (n_33), .Y (n_34));
  NAND2X1 g1131__1881(.A (G132), .B (n_33), .Y (n_32));
  AOI22X1 g1128__5115(.A0 (G12), .A1 (n_15), .B0 (G11), .B1 (n_23), .Y
       (n_31));
  NOR2X1 g1134__7482(.A (G0), .B (n_19), .Y (n_30));
  DFFHQX1 DFF_13_q_reg(.CK (CK), .D (n_16), .Q (G23));
  OR3X1 g1137__4733(.A (n_29), .B (G11), .C (n_20), .Y (n_51));
  DFFHQX1 DFF_12_q_reg(.CK (CK), .D (n_17), .Q (G22));
  AOI21X1 g1145__6161(.A0 (G13), .A1 (n_22), .B0 (n_26), .Y (n_28));
  NAND2BX1 g1139__9315(.AN (n_35), .B (n_26), .Y (n_27));
  AOI31X1 g1138__9945(.A0 (G10), .A1 (n_24), .A2 (n_23), .B0 (G23), .Y
       (n_25));
  NAND2X1 g1147__2883(.A (n_22), .B (n_12), .Y (n_50));
  AND4X1 g1135__2346(.A (G22), .B (n_29), .C (n_24), .D (n_23), .Y
       (n_21));
  OR2X1 g1142__1666(.A (n_24), .B (n_20), .Y (n_40));
  INVX1 g1143(.A (n_42), .Y (n_33));
  XNOR2X1 g1144__7410(.A (n_18), .B (n_14), .Y (n_19));
  NOR2X1 g1141__6417(.A (G0), .B (n_6), .Y (n_17));
  NOR2X1 g1140__5477(.A (G0), .B (n_5), .Y (n_16));
  OAI22X1 g1146__2398(.A0 (G13), .A1 (n_14), .B0 (G11), .B1 (n_13), .Y
       (n_15));
  AOI21X1 g1153__5107(.A0 (G22), .A1 (n_18), .B0 (n_8), .Y (n_12));
  OR2X1 g1155__6260(.A (n_10), .B (n_23), .Y (n_11));
  NAND2X1 g1154__4319(.A (n_22), .B (n_8), .Y (n_9));
  NOR2BX1 g1151__8428(.AN (n_23), .B (G22), .Y (n_26));
  OR3X1 g1148__5526(.A (G15), .B (n_29), .C (n_3), .Y (n_42));
  DFFHQX1 DFF_0_q_reg(.CK (CK), .D (n_4), .Q (G10));
  OR2X1 g1149__6783(.A (G14), .B (n_7), .Y (n_41));
  OR2X1 g1150__3680(.A (G12), .B (n_7), .Y (n_20));
  XNOR2X1 g1156__1617(.A (G2), .B (G22), .Y (n_6));
  XNOR2X1 g1157__2802(.A (G1), .B (G23), .Y (n_5));
  OR2X1 g1164__1705(.A (G14), .B (n_24), .Y (n_35));
  INVX1 g1158(.A (n_4), .Y (n_38));
  NAND2X1 g1162__5122(.A (G13), .B (n_29), .Y (n_8));
  AND2X1 g1165__8246(.A (G13), .B (n_18), .Y (n_23));
  NOR2X1 g1159__7098(.A (G12), .B (G13), .Y (n_3));
  OR2X1 g1161__6131(.A (G15), .B (G13), .Y (n_7));
  NAND2X1 g1163__1881(.A (G10), .B (G11), .Y (n_14));
  NOR2X1 g1160__5115(.A (G0), .B (G10), .Y (n_4));
  INVX1 g1167(.A (G66), .Y (n_2));
  INVX1 g1171(.A (G15), .Y (n_22));
  INVX1 g1168(.A (G12), .Y (n_18));
  INVX1 g1173(.A (G14), .Y (n_29));
  INVX1 g1166(.A (G133), .Y (n_1));
  INVX1 g1170(.A (G117), .Y (n_0));
  INVX1 g1172(.A (G10), .Y (n_10));
  INVX1 g1169(.A (G13), .Y (n_13));
  INVX1 g1174(.A (G11), .Y (n_24));
endmodule

