/* Generated by Tessent Shell 2022.4 at Mon Mar 24 11:35:00 IST 2025 */
module mcrb(mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, skew_addr_cntr_o, mc_rb_fuse_vld_i, 
            mc_rb_ef1_sclk_i, SI, SO, SE, ts_si, ts_so, scan_en);
  input  [0:0] ts_si;
  input  mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i, 
         mc_rb_ef1_sclk_i, SI, SE, scan_en;
  output [4:0] skew_addr_cntr_o;
  output [0:0] ts_so;
  output SO;

  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, UNCONNECTED3, 
       UNCONNECTED4, mc_rb_fuse_vld_q, n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7, 
       n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16, 
       ts_lockup_latchn_clkc1_intno5_, ts_pbuf_extsi6_;

  assign ts_so = ts_lockup_latchn_clkc1_intno5_;
  SDFFR_X2 \skew_addr_cntr_reg[4] (
      .CK(mc_rb_ef1_sclk_i), .D(n_16), .RN(gctl_rclk_orst_n_i), .SE(scan_en), .SI(ts_pbuf_extsi6_), 
      .Q(skew_addr_cntr_o[4]), .QN(UNCONNECTED)
  );
  SDFFR_X2 \skew_addr_cntr_reg[3] (
      .CK(mc_rb_ef1_sclk_i), .D(n_15), .RN(gctl_rclk_orst_n_i), .SE(scan_en), .SI(skew_addr_cntr_o[4]), 
      .Q(skew_addr_cntr_o[3]), .QN(UNCONNECTED0)
  );
  SDFFR_X2 \skew_addr_cntr_reg[1] (
      .CK(mc_rb_ef1_sclk_i), .D(n_12), .RN(gctl_rclk_orst_n_i), .SE(scan_en), .SI(skew_addr_cntr_o[3]), 
      .Q(skew_addr_cntr_o[1]), .QN(UNCONNECTED1)
  );
  SDFFR_X2 \skew_addr_cntr_reg[2] (
      .CK(mc_rb_ef1_sclk_i), .D(n_11), .RN(gctl_rclk_orst_n_i), .SE(scan_en), .SI(skew_addr_cntr_o[1]), 
      .Q(skew_addr_cntr_o[2]), .QN(UNCONNECTED2)
  );
  SDFFR_X2 \skew_addr_cntr_reg[0] (
      .CK(mc_rb_ef1_sclk_i), .D(n_13), .RN(gctl_rclk_orst_n_i), .SE(scan_en), .SI(skew_addr_cntr_o[2]), 
      .Q(skew_addr_cntr_o[0]), .QN(UNCONNECTED3)
  );
  NOR2_X2 g405__2398(
      .A1(n_10), .A2(n_14), .ZN(n_16)
  );
  NOR2_X2 g408__5107(
      .A1(n_14), .A2(n_9), .ZN(n_15)
  );
  NOR2_X2 g413__6260(
      .A1(n_14), .A2(skew_addr_cntr_o[0]), .ZN(n_13)
  );
  NOR2_X2 g414__4319(
      .A1(n_14), .A2(n_2), .ZN(n_12)
  );
  NOR2_X2 g415__8428(
      .A1(n_14), .A2(n_4), .ZN(n_11)
  );
  XNOR2_X2 g407__5526(
      .A(n_8), .B(skew_addr_cntr_o[4]), .ZN(n_10)
  );
  AOI221_X2 g417__6783(
      .A(n_6), .B1(n_5), .B2(skew_addr_cntr_o[4]), .C1(n_0), .C2(mc_rb_fuse_vld_q), 
      .ZN(n_14)
  );
  XNOR2_X2 g411__3680(
      .A(n_7), .B(skew_addr_cntr_o[3]), .ZN(n_9)
  );
  AND2_X2 g416__1617(
      .A1(n_7), .A2(skew_addr_cntr_o[3]), .ZN(n_8)
  );
  AOI21_X2 g418__2802(
      .A(skew_addr_cntr_o[4]), .B1(n_5), .B2(n_1), .ZN(n_6)
  );
  XNOR2_X2 g419__1705(
      .A(n_3), .B(skew_addr_cntr_o[2]), .ZN(n_4)
  );
  AND2_X2 g420__5122(
      .A1(n_3), .A2(skew_addr_cntr_o[2]), .ZN(n_7)
  );
  XNOR2_X2 g421__8246(
      .A(skew_addr_cntr_o[0]), .B(skew_addr_cntr_o[1]), .ZN(n_2)
  );
  SDFFR_X1 mc_rb_fuse_vld_q_reg(
      .CK(mc_rb_ef1_sclk_i), .D(mc_rb_fuse_vld_i), .RN(gctl_rclk_orst_n_i), .SE(scan_en), 
      .SI(skew_addr_cntr_o[0]), .Q(mc_rb_fuse_vld_q), .QN(UNCONNECTED4)
  );
  NOR2_X2 g423__7098(
      .A1(skew_addr_cntr_o[2]), .A2(skew_addr_cntr_o[3]), .ZN(n_5)
  );
  NOR2_X2 g424__6131(
      .A1(skew_addr_cntr_o[1]), .A2(skew_addr_cntr_o[0]), .ZN(n_1)
  );
  AND2_X2 g425__1881(
      .A1(skew_addr_cntr_o[1]), .A2(skew_addr_cntr_o[0]), .ZN(n_3)
  );
  INV_X4 g426(
      .A(mc_rb_ef1_svld_i), .ZN(n_0)
  );
  DLL_X2 ts_lockup_latchn_clkc1_intno5_i(
      .D(mc_rb_fuse_vld_q), .GN(mc_rb_ef1_sclk_i), .Q(ts_lockup_latchn_clkc1_intno5_)
  );
  CLKBUF_X3 tessent_persistent_cell_buf_extsi6_i(
      .A(ts_si), .Z(ts_pbuf_extsi6_)
  );
endmodule

