/* Generated by Tessent Shell 2022.4 at Fri Mar 14 12:41:13 IST 2025 */
module s298(GND, VDD, CK, G0, G1, G117, G118, G132, G133, G2, G66, G67, SI, SO, 
            SE);
  input  GND, VDD, CK, G0, G1, G2, SI, SE;
  output G117, G118, G132, G133, G66, G67, SO;

  wire G10, G11, G12, G13, G14, G15, G22, G23, UNCONNECTED, UNCONNECTED0, 
       UNCONNECTED1, UNCONNECTED2, UNCONNECTED3, n_0, n_1, n_2, n_3, n_4, n_5, 
       n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17, 
       n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29, 
       n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41, 
       n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53, 
       n_54, n_55, n_56;

  SDFF_X2 DFF_10_q_reg(
      .CK(CK), .D(n_56), .SE(1'b0), .SI(1'b0), .Q(G132), .QN(n_0)
  );
  SDFF_X2 DFF_9_q_reg(
      .CK(CK), .D(n_55), .SE(1'b0), .SI(1'b0), .Q(G118), .QN(UNCONNECTED)
  );
  OAI221_X2 g1322__2398(
      .A(n_31), .B1(n_52), .B2(G10), .C1(n_39), .C2(n_0), .ZN(n_56)
  );
  SDFF_X2 DFF_6_q_reg(
      .CK(CK), .D(n_54), .SE(1'b0), .SI(1'b0), .Q(G66), .QN(UNCONNECTED0)
  );
  SDFF_X2 DFF_5_q_reg(
      .CK(CK), .D(n_53), .SE(1'b0), .SI(1'b0), .Q(G15), .QN(n_11)
  );
  SDFF_X2 DFF_4_q_reg(
      .CK(CK), .D(n_50), .SE(1'b0), .SI(1'b0), .Q(G14), .QN(n_41)
  );
  OAI21_X2 g1321__5107(
      .A(n_48), .B1(n_46), .B2(G14), .ZN(n_55)
  );
  SDFF_X2 DFF_3_q_reg(
      .CK(CK), .D(n_51), .SE(1'b0), .SI(1'b0), .Q(G13), .QN(UNCONNECTED1)
  );
  INV_X2 g1327(
      .A(n_49), .ZN(n_54)
  );
  NOR2_X2 g1328__6260(
      .A1(n_52), .A2(G0), .ZN(n_53)
  );
  NOR2_X2 g1332__4319(
      .A1(n_43), .A2(G0), .ZN(n_51)
  );
  SDFF_X2 DFF_8_q_reg(
      .CK(CK), .D(n_40), .SE(1'b0), .SI(1'b0), .Q(G117), .QN(n_3)
  );
  NOR2_X2 g1329__8428(
      .A1(n_42), .A2(G0), .ZN(n_50)
  );
  AOI22_X2 g1330__5526(
      .A1(n_45), .A2(n_41), .B1(n_47), .B2(G66), .ZN(n_49)
  );
  AOI221_X2 g1337__6783(
      .A(n_32), .B1(G15), .B2(n_44), .C1(n_47), .C2(G118), .ZN(n_48)
  );
  SDFF_X2 DFF_7_q_reg(
      .CK(CK), .D(n_38), .SE(1'b0), .SI(1'b0), .Q(G67), .QN(n_2)
  );
  AOI21_X2 g1331__3680(
      .A(n_45), .B1(n_44), .B2(G13), .ZN(n_46)
  );
  AOI21_X2 g1340__1617(
      .A(n_28), .B1(n_34), .B2(G15), .ZN(n_52)
  );
  AOI211_X2 g1346__2802(
      .A(n_16), .B(n_26), .C1(n_14), .C2(G13), .ZN(n_43)
  );
  SDFF_X2 DFF_1_q_reg(
      .CK(CK), .D(n_35), .SE(1'b0), .SI(1'b0), .Q(G11), .QN(n_24)
  );
  XNOR2_X2 g1338__1705(
      .A(n_29), .B(n_41), .ZN(n_42)
  );
  OAI211_X2 g1339__5122(
      .A(n_37), .B(n_36), .C1(n_39), .C2(n_3), .ZN(n_40)
  );
  SDFF_X2 DFF_11_q_reg(
      .CK(CK), .D(n_30), .SE(1'b0), .SI(1'b0), .Q(G133), .QN(n_1)
  );
  SDFF_X2 DFF_2_q_reg(
      .CK(CK), .D(n_25), .SE(1'b0), .SI(1'b0), .Q(G12), .QN(n_13)
  );
  OAI221_X2 g1336__8246(
      .A(n_37), .B1(n_39), .B2(n_2), .C1(n_36), .C2(G11), .ZN(n_38)
  );
  OAI21_X2 g1347__7098(
      .A(n_22), .B1(n_33), .B2(G22), .ZN(n_45)
  );
  NOR2_X2 g1345__6131(
      .A1(n_21), .A2(G0), .ZN(n_35)
  );
  OR3_X2 g1350__1881(
      .A1(n_33), .A2(G14), .A3(G22), .ZN(n_34)
  );
  INV_X2 g1353(
      .A(n_31), .ZN(n_32)
  );
  OAI22_X2 g1344__5115(
      .A1(n_36), .A2(n_4), .B1(n_39), .B2(n_1), .ZN(n_30)
  );
  AOI21_X2 g1351__7482(
      .A(G23), .B1(n_20), .B2(n_27), .ZN(n_29)
  );
  SDFF_X2 DFF_13_q_reg(
      .CK(CK), .D(n_19), .SE(1'b0), .SI(1'b0), .Q(G23), .QN(UNCONNECTED2)
  );
  SDFF_X2 DFF_12_q_reg(
      .CK(CK), .D(n_18), .SE(1'b0), .SI(1'b0), .Q(G22), .QN(UNCONNECTED3)
  );
  AND4_X2 g1356__4733(
      .A1(n_27), .A2(n_24), .A3(n_41), .A4(G22), .ZN(n_28)
  );
  INV_X1 g1359(
      .A(n_33), .ZN(n_26)
  );
  NOR2_X2 g1341__6161(
      .A1(n_17), .A2(G0), .ZN(n_25)
  );
  NAND3_X2 g1358__9315(
      .A1(n_23), .A2(n_24), .A3(G14), .ZN(n_31)
  );
  NAND2_X2 g1352__9945(
      .A1(n_23), .A2(G11), .ZN(n_37)
  );
  OAI211_X2 g1354__2883(
      .A(n_11), .B(G13), .C1(n_6), .C2(G11), .ZN(n_22)
  );
  AOI22_X2 g1357__2346(
      .A1(n_20), .A2(n_12), .B1(G11), .B2(n_44), .ZN(n_21)
  );
  NAND2_X2 g1362__1666(
      .A1(n_27), .A2(G11), .ZN(n_33)
  );
  NOR2_X2 g1348__7410(
      .A1(n_9), .A2(G0), .ZN(n_19)
  );
  NOR2_X2 g1349__6417(
      .A1(n_10), .A2(G0), .ZN(n_18)
  );
  XOR2_X2 g1355__5477(
      .A(n_15), .B(G12), .Z(n_17)
  );
  INV_X4 g1364(
      .A(n_39), .ZN(n_47)
  );
  NOR2_X2 g1360__2398(
      .A1(n_8), .A2(G12), .ZN(n_23)
  );
  NOR3_X1 g1366__5107(
      .A1(n_15), .A2(G13), .A3(n_13), .ZN(n_16)
  );
  NAND2_X2 g1361__6260(
      .A1(n_7), .A2(n_41), .ZN(n_36)
  );
  SDFF_X2 DFF_0_q_reg(
      .CK(CK), .D(n_5), .SE(1'b0), .SI(1'b0), .Q(G10), .QN(n_44)
  );
  OAI21_X2 g1367__4319(
      .A(G10), .B1(G11), .B2(n_13), .ZN(n_14)
  );
  INV_X4 g1371(
      .A(n_12), .ZN(n_27)
  );
  OAI211_X2 g1369__8428(
      .A(n_11), .B(G14), .C1(G12), .C2(G13), .ZN(n_39)
  );
  XNOR2_X2 g1365__5526(
      .A(G22), .B(G2), .ZN(n_10)
  );
  XNOR2_X2 g1368__6783(
      .A(G23), .B(G1), .ZN(n_9)
  );
  INV_X2 g1370(
      .A(n_7), .ZN(n_8)
  );
  NAND2_X1 g1372__3680(
      .A1(G22), .A2(n_13), .ZN(n_6)
  );
  NOR2_X2 g1377__1617(
      .A1(G11), .A2(n_44), .ZN(n_20)
  );
  NAND2_X2 g1374__2802(
      .A1(G13), .A2(n_13), .ZN(n_12)
  );
  NOR2_X2 g1375__1705(
      .A1(G10), .A2(G0), .ZN(n_5)
  );
  NOR2_X2 g1373__5122(
      .A1(G15), .A2(G13), .ZN(n_7)
  );
  NAND2_X2 g1376__8246(
      .A1(G11), .A2(G12), .ZN(n_4)
  );
  NAND2_X2 g1378__7098(
      .A1(G11), .A2(G10), .ZN(n_15)
  );
endmodule

